# basic options
title: interym  
author: interym
email: interym@kyosk.org  
description: news from the blog
twitch_username: intylive
github_username:  interym

# Build settings
markdown: kramdown
theme: minima
